"use strict";
console.log("Hello world");
var userName = "Naveed";
var num1 = 22;
var num2 = 23;
var result = num1 + num2;
var result = num1 * num2;
console.log(userName);
console.log(num1);
console.log(result);
